// Generated by Wrangler on Mon Apr 22 2024 21:35:38 GMT+0200 (hora de verano de Europa central)
// by running `wrangler types`

interface Env {
	API_URL: "https://webhook.site/d540da87-1a79-4168-a455-4ef524049a61";
}
